name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  monorepo-ci:
    name: Typecheck, Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack
        run: npx -y corepack@latest enable
      - name: Pin Yarn 4
        run: corepack prepare yarn@4.1.0 --activate
      - name: Verify Node/Yarn versions
        run: |
          node -v
          corepack yarn --version
      - name: Cache Yarn (Yarn 4)
        uses: actions/cache@v4
        with:
          path: |
            kateri-monorepo/.yarn/cache
          key: ${{ runner.os }}-yarn4-${{ hashFiles('kateri-monorepo/yarn.lock') }}

      - name: Install dependencies
        working-directory: kateri-monorepo
        run: corepack yarn install --immutable

      - name: Typecheck all workspaces
        working-directory: kateri-monorepo
        run: corepack yarn typecheck

      - name: Lint all workspaces
        working-directory: kateri-monorepo
        run: |
          corepack yarn lint || {
            echo "Linting failed. To see details locally, run: yarn lint";
            exit 1;
          }

      - name: Run tests across workspaces
        working-directory: kateri-monorepo
        run: corepack yarn test

      - name: Build all workspaces
        working-directory: kateri-monorepo
        run: corepack yarn build
