name: Cleanup Legacy Gen1 Functions

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack
        run: npx -y corepack@latest enable
      
      - name: Pin Yarn 4
        run: corepack prepare yarn@4.1.0 --activate

      - name: Delete legacy dailyHealthCheck (Gen1)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          corepack yarn dlx firebase-tools functions:delete dailyHealthCheck --region us-central1 --project kcm-firebase-b7d6a --force

      - name: Deploy default codebase to finalize cleanup
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          corepack yarn dlx firebase-tools deploy --only functions:default --project kcm-firebase-b7d6a --non-interactive --force
