name: Deploy Gen2 Functions

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  deploy-gen2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Enable Corepack
        run: npx -y corepack@latest enable
      - name: Pin Yarn 4
        run: corepack prepare yarn@4.1.0 --activate
      - name: Verify Node/Yarn versions
        run: |
          node -v
          yarn --version
      - name: Install
        working-directory: kateri-monorepo
        run: yarn install --immutable
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "Missing required secret: FIREBASE_TOKEN. Create a repo secret named FIREBASE_TOKEN with your firebase login:ci token." >&2
            exit 1
          fi
      - name: Authenticate to Firebase (Service Account)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy gen2 codebase (with SA + token)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          yarn dlx firebase-tools deploy \
            --only functions:gen2 \
            --project kcm-firebase-b7d6a \
            --non-interactive \
            --token "$FIREBASE_TOKEN"
      - name: Deploy gen2 codebase (token-only)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT == '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          yarn dlx firebase-tools deploy \
            --only functions:gen2 \
            --project kcm-firebase-b7d6a \
            --non-interactive \
            --token "$FIREBASE_TOKEN"
