name: Deploy Gen2 Functions

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  deploy-gen2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack
        run: corepack enable
      - name: Install
        run: yarn --cwd kateri-monorepo install --immutable
      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - name: Deploy gen2 codebase
        run: |
          yarn dlx firebase-tools deploy --only functions:gen2 --project kcm-firebase-b7d6a --non-interactive
