name: Emulator Smoke

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main, develop]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Enable Corepack
        run: npx -y corepack@latest enable
      - name: Pin Yarn 4
        run: corepack prepare yarn@4.1.0 --activate
      - name: Verify Node/Yarn versions
        run: |
          node -v
          yarn --version
      - name: Install (non-immutable)
        working-directory: kateri-monorepo
        run: corepack yarn install
      - name: Build functions
        run: |
          corepack yarn --cwd kateri-monorepo workspace @kateri/functions run build
          corepack yarn --cwd kateri-monorepo workspace @kateri/functions-gen2 run build
      - name: Run emulators smoke
        env:
          FB_PROJECT_ID: kcm-firebase-b7d6a
          FB_REGION: us-central1
          FB_DB_ID: kcm-db
        run: |
          npx --yes firebase-tools emulators:exec --only functions,firestore --project kcm-firebase-b7d6a -- node kateri-monorepo/scripts/emulator-smoke.js
