name: Deploy Hosting Preview

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Preview channel name (e.g., feature-xyz or pr-123)"
        required: true
      expires:
        description: "Expiry (e.g., 7d, 12h). Max 30d"
        required: false
        default: "7d"

permissions:
  contents: read
  id-token: write

jobs:
  preview:
    name: Build and deploy web to Hosting preview
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: kcm-firebase-b7d6a
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack and pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.1.0 --activate
          yarn --version

      - name: Cache Yarn (Yarn 4)
        uses: actions/cache@v4
        with:
          path: |
            kateri-monorepo/.yarn/cache
          key: ${{ runner.os }}-yarn4-${{ hashFiles('kateri-monorepo/yarn.lock') }}

      - name: Install dependencies (monorepo)
        working-directory: kateri-monorepo
        run: yarn install --immutable

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Build web app
        working-directory: kateri-monorepo
        run: yarn workspace @kateri/web build

      - name: Deploy to Hosting preview channel
        id: deploy
        env:
          CHANNEL: ${{ github.event.inputs.channel }}
          EXPIRES: ${{ github.event.inputs.expires }}
        run: |
          set -euo pipefail
          yarn dlx firebase-tools@13.29.0 hosting:channel:deploy "$CHANNEL" \
            --project "$PROJECT_ID" \
            --expires "$EXPIRES" \
            --non-interactive \
            --json > deploy.json
          echo "Deploy output:" && cat deploy.json
          URL=$(node -e "const o=require('./deploy.json');console.log(o.result?.[0]?.url||o.result?.url||'');")
          echo "preview_url=$URL" >> "$GITHUB_OUTPUT"

      - name: Summarize
        run: |
          echo "Preview URL: ${{ steps.deploy.outputs.preview_url }}" >> $GITHUB_STEP_SUMMARY
