name: Secrets Sanity Check

on:
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: kcm-firebase-b7d6a
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate GitHub secrets presence (masked)
        shell: bash
        run: |
          set -euo pipefail
          missing=0
          for n in GCP_WORKLOAD_IDENTITY_PROVIDER GCP_SERVICE_ACCOUNT_EMAIL; do
            if [ -n "${!n:-}" ]; then
              echo "::notice title=${n}::present"
            else
              echo "::error title=${n}::missing"
              missing=1
            fi
          done
          exit $missing

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true

      - name: WIF ADC sanity check
        shell: bash
        run: |
          set -euo pipefail
          gcloud config set project "$PROJECT_ID" >/dev/null
          echo "Active account:" $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
          gcloud auth print-access-token >/dev/null
          echo "WIF ADC OK"

      - name: Verify SENTRY_DSN exists in Secret Manager (GCP)
        shell: bash
        run: |
          set -euo pipefail
          if gcloud secrets versions list SENTRY_DSN --project "$PROJECT_ID" --format='value(name)' | head -n1 | grep -q .; then
            echo "SENTRY_DSN present in GCP Secret Manager"
          else
            echo "::error title=SENTRY_DSN missing in GCP::Create secret 'SENTRY_DSN' with at least one version and grant access to runtime/deploy SAs"
            exit 1
          fi

      - name: Summary
        if: always()
        run: |
          {
            echo "GitHub secrets presence:"
            for n in GCP_WORKLOAD_IDENTITY_PROVIDER GCP_SERVICE_ACCOUNT_EMAIL; do
              if [ -n "${!n:-}" ]; then echo "- $n: present"; else echo "- $n: missing"; fi
            done
            echo
            echo "GCP secrets:"
            gcloud secrets describe SENTRY_DSN --project "$PROJECT_ID" >/dev/null 2>&1 && echo "- SENTRY_DSN: present" || echo "- SENTRY_DSN: missing"
          } >> $GITHUB_STEP_SUMMARY
